# -*- coding: utf-8 -*-
"""Concrete_Compressive_Strength_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hpi05YJ2x5lqCSt5WuTqGnI1R98XqNqe
"""

# Install UCI dataset package
# Import required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import joblib

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from ucimlrepo import fetch_ucirepo

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# Fetch Concrete Compressive Strength dataset from UCI
concrete = fetch_ucirepo(id=165)

# Separate features and target
X = concrete.data.features
y = concrete.data.targets

# Display first 5 rows
print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

print("Dataset shape:", X.shape)

print("\nFeature names:")
print(X.columns.tolist())

print("\nMissing values:")
print(X.isnull().sum())

print("\nDataset statistics:")
print(X.describe())

X.columns = [
    "Cement",
    "Blast_Furnace_Slag",
    "Fly_Ash",
    "Water",
    "Superplasticizer",
    "Coarse_Aggregate",
    "Fine_Aggregate",
    "Age"
]

y.columns = ["Compressive_Strength"]

print(X.head())
print(y.head())

# Plot distribution of compressive strength

plt.figure(figsize=(8,5))

plt.hist(
    y["Compressive_Strength"],
    bins=30,
    edgecolor="black"
)

plt.xlabel("Compressive Strength (MPa)")
plt.ylabel("Number of Samples")
plt.title("Distribution of Concrete Compressive Strength")

plt.show()

# Combine features and target
data = pd.concat([X, y], axis=1)

# Calculate correlations
correlation = data.corr()

# Display correlation with compressive strength
print(
    correlation["Compressive_Strength"]
    .sort_values(ascending=False)
)

plt.figure(figsize=(10,7))

plt.imshow(correlation, cmap="coolwarm", aspect="auto")

plt.colorbar()

plt.xticks(
    range(len(correlation.columns)),
    correlation.columns,
    rotation=90
)

plt.yticks(
    range(len(correlation.columns)),
    correlation.columns
)

plt.title("Correlation Heatmap")

plt.tight_layout()

plt.show()

# Split dataset into training and testing sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

# Create Linear Regression model
linear_model = LinearRegression()

# Train model
linear_model.fit(X_train, y_train)

# Make predictions
linear_predictions = linear_model.predict(X_test)

# Calculate evaluation metrics
linear_mae = mean_absolute_error(
    y_test,
    linear_predictions
)

linear_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        linear_predictions
    )
)

linear_r2 = r2_score(
    y_test,
    linear_predictions
)

print("Linear Regression")
print("----------------------")
print("MAE :", round(linear_mae, 3))
print("RMSE:", round(linear_rmse, 3))
print("R²  :", round(linear_r2, 3))

# Create Decision Tree model
tree_model = DecisionTreeRegressor(
    random_state=42,
    max_depth=6
)

# Train model
tree_model.fit(X_train, y_train)

# Make predictions
tree_predictions = tree_model.predict(X_test)

# Evaluation
tree_mae = mean_absolute_error(
    y_test,
    tree_predictions
)

tree_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        tree_predictions
    )
)

tree_r2 = r2_score(
    y_test,
    tree_predictions
)

print("Decision Tree")
print("----------------------")
print("MAE :", round(tree_mae, 3))
print("RMSE:", round(tree_rmse, 3))
print("R²  :", round(tree_r2, 3))

# Create Random Forest model
rf_model = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    max_depth=12
)

# Train model
rf_model.fit(X_train, y_train.values.ravel())

# Make predictions
rf_predictions = rf_model.predict(X_test)

# Evaluation
rf_mae = mean_absolute_error(
    y_test,
    rf_predictions
)

rf_rmse = np.sqrt(
    mean_squared_error(
        y_test,
        rf_predictions
    )
)

rf_r2 = r2_score(
    y_test,
    rf_predictions
)

print("Random Forest")
print("----------------------")
print("MAE :", round(rf_mae, 3))
print("RMSE:", round(rf_rmse, 3))
print("R²  :", round(rf_r2, 3))

results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest"
    ],

    "MAE": [
        linear_mae,
        tree_mae,
        rf_mae
    ],

    "RMSE": [
        linear_rmse,
        tree_rmse,
        rf_rmse
    ],

    "R2": [
        linear_r2,
        tree_r2,
        rf_r2
    ]
})

print(results)

plt.figure(figsize=(8,5))

plt.bar(
    results["Model"],
    results["R2"]
)

plt.ylabel("R² Score")
plt.xlabel("Model")
plt.title("Comparison of Model Performance")

plt.xticks(rotation=15)

plt.ylim(0, 1)

plt.tight_layout()

plt.show()

plt.figure(figsize=(7,7))

plt.scatter(
    y_test,
    rf_predictions,
    alpha=0.7
)

# Perfect prediction line
minimum = min(
    y_test["Compressive_Strength"].min(),
    rf_predictions.min()
)

maximum = max(
    y_test["Compressive_Strength"].max(),
    rf_predictions.max()
)

plt.plot(
    [minimum, maximum],
    [minimum, maximum],
    linestyle="--"
)

plt.xlabel("Actual Compressive Strength (MPa)")
plt.ylabel("Predicted Compressive Strength (MPa)")

plt.title(
    "Actual vs Predicted Concrete Compressive Strength"
)

plt.tight_layout()

plt.show()

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance)

plt.figure(figsize=(9,5))

plt.barh(
    importance["Feature"],
    importance["Importance"]
)

plt.xlabel("Importance")
plt.ylabel("Feature")

plt.title(
    "Random Forest Feature Importance"
)

plt.gca().invert_yaxis()

plt.tight_layout()

plt.show()

# Example concrete mix

new_concrete = pd.DataFrame({
    "Cement": [350],
    "Blast_Furnace_Slag": [100],
    "Fly_Ash": [50],
    "Water": [180],
    "Superplasticizer": [8],
    "Coarse_Aggregate": [1000],
    "Fine_Aggregate": [700],
    "Age": [28]
})

prediction = rf_model.predict(new_concrete)

print(
    "Predicted Compressive Strength:",
    round(prediction[0], 2),
    "MPa"
)

import joblib

joblib.dump(
    rf_model,
    "concrete_strength_random_forest.pkl"
)

print("Model saved successfully.")